version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/etc/nginx/conf.d/:/etc/nginx/conf.d/
      - /var/log/nginx:/var/log/nginx
      - /opt/certs:/etc/ssl
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
